export { default as Header } from './Header';
export { default as Hero } from './Hero';
export { default as WhyChooseUs } from './WhyChooseUs';
export { default as Process } from './Process';
export { default as RecentProjects } from './RecentProjects';
export { default as Testimonials } from './Testimonials';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Footer } from './Footer';
